import {
  faEye,
  faPencilAlt,
  faTimes,
  faBars,
  faPhoneAlt,
  faHomeAlt,
  faEnvelope,
  faInfo,
  faSearch,
  faTrashAlt,
  faTruckFast,
  faDiamond,
  faLongArrowLeft,
  faStar,
  faHeart,
  faAngleRight,
} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  edit: faPencilAlt,
  del: faTimes,
  eye: faEye,
  bars: faBars,
  tel: faPhoneAlt,
  home: faHomeAlt,
  env: faEnvelope,
  info: faInfo,
  search: faSearch,
  truck: faTruckFast,
  mat: faEnvelope,
  dim: faDiamond,
  heart: faHeart,
  arrLeft: faLongArrowLeft,
  trash: faTrashAlt,
  star: faStar,
  angRight: faAngleRight,
};
